### ISSUE TITLE
not working with ecl

### ISSUE THREAD

**Issue by vrx** [nikodemus/pileup#3]
Hi,
It seems that pileup does not work with ECL (tested on linux and osx)

```
(ql:quickload :pileup-tests)
(pileup-tests::heap-basics)
```
> The variable PILEUP::%SIZE is unbound.

By advance many thanks for your help.
V

I have been using : 
VERSION "21.2.1"
      VCS-ID "UNKNOWN"
          OS "Linux"
  OS-VERSION "5.4.0-66-generic"
MACHINE-TYPE "x86_64"
    FEATURES (:SWANK :SERVE-EVENT :QUICKLISP :QUICKLISP-SUPPORT-HTTPS
              :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-UNIX
              :NON-BASE-CHARS-EXIST-P :ASDF-UNICODE :ROS.INIT :WALKER :CDR-1
              :CDR-5 :LINUX :FORMATTER :CDR-7 :ECL-WEAK-HASH :LITTLE-ENDIAN
              :LONG-LONG :UINT64-T :UINT32-T :UINT16-T :COMPLEX-FLOAT
              :LONG-FLOAT :UNICODE :DFFI :CLOS-STREAMS :CMU-FORMAT :UNIX
              :ECL-PDE :DLOPEN :CLOS :THREADS :BOEHM-GC :ANSI-CL :COMMON-LISP
              :FLOATING-POINT-EXCEPTIONS :IEEE-FLOATING-POINT
              :PACKAGE-LOCAL-NICKNAMES :CDR-14 :PREFIXED-API :FFI :X86_64
              :COMMON :ECL)

**Comment by nikodemus** [comment]
ECL bug, fixed in https://gitlab.com/embeddable-common-lisp/ecl/-/commit/977e2fab34abb9182e0d04e654a26ec75f37d67e
